#!/usr/bin/env bash

set -euo pipefail

if [[ -v "IN_NIX_SHELL" && "${name:-}" == "infra-env" ]]; then
  nix-fast-build --skip-cached --fail-fast
else
  nix develop --command nix-fast-build --skip-cached --fail-fast
fi
